/* The following code was generated by JFlex 1.7.0 */


/* Vacío */


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>rmj.lex</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int METODO = 2;
  public static final int DECLARACION = 4;
  public static final int TEXTO = 6;
  public static final int SALIDA = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\12\0\1\10\1\11\1\11\1\11\22\0\1\3\1\0\1\5\5\0"+
    "\1\27\1\36\1\0\1\6\4\0\12\2\1\0\1\35\1\0\1\4"+
    "\3\0\22\1\1\12\7\1\1\0\1\7\2\0\1\1\1\0\1\31"+
    "\1\1\1\30\1\1\1\16\1\1\1\34\1\1\1\24\2\1\1\26"+
    "\1\17\1\25\1\20\1\22\1\1\1\23\1\14\1\15\1\21\3\1"+
    "\1\13\1\1\1\32\1\0\1\33\7\0\1\11\u1fa2\0\1\11\1\11"+
    "\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\0\1\2\2\3\1\4\1\2\1\5"+
    "\1\2\1\6\1\5\1\7\1\10\1\2\1\6\1\11"+
    "\1\12\1\1\1\13\1\1\1\2\1\14\3\2\1\3"+
    "\2\0\2\5\3\0\1\1\1\0\1\15\1\3\2\5"+
    "\1\6\1\3\2\5\1\2\4\5\1\0\1\5\1\2"+
    "\1\5\1\0\1\5\1\0\1\5\1\0\1\5\1\0"+
    "\1\2\1\5\1\0\1\5\1\0\1\5\1\0\1\5"+
    "\1\0\1\5\1\0\1\5\1\0\1\5\1\0\1\5"+
    "\1\16";

  private static int [] zzUnpackAction() {
    int [] result = new int[79];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\37\0\76\0\135\0\174\0\233\0\272\0\331"+
    "\0\233\0\370\0\u0117\0\u0136\0\u0155\0\u0174\0\370\0\u0193"+
    "\0\u01b2\0\u01d1\0\233\0\233\0\u01f0\0\u020f\0\u022e\0\u024d"+
    "\0\u026c\0\u020f\0\u028b\0\u02aa\0\u02c9\0\370\0\u0136\0\u02e8"+
    "\0\u0307\0\u01b2\0\u020f\0\u0326\0\233\0\u024d\0\u024d\0\u0345"+
    "\0\u0364\0\u0383\0\233\0\u03a2\0\u03c1\0\u03e0\0\272\0\u03ff"+
    "\0\u041e\0\u043d\0\u045c\0\u047b\0\u049a\0\u047b\0\u04b9\0\u04d8"+
    "\0\u04f7\0\u0516\0\u0535\0\u0554\0\u0573\0\u0592\0\u0592\0\u05b1"+
    "\0\u05d0\0\u05ef\0\u060e\0\u062d\0\u064c\0\u066b\0\u068a\0\u06a9"+
    "\0\u06c8\0\u06e7\0\u0706\0\u0725\0\u0744\0\u0763\0\370";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[79];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\10\6\15\7\1\6\1\10\1\7\1\11"+
    "\1\6\1\7\2\6\1\12\1\13\1\12\1\14\1\15"+
    "\5\12\1\16\14\13\1\12\2\13\1\12\1\17\1\13"+
    "\2\12\1\6\1\20\1\6\1\21\1\22\1\23\2\6"+
    "\1\24\1\6\15\20\1\6\2\20\2\6\1\20\1\24"+
    "\1\6\5\25\1\26\1\25\1\27\27\25\1\30\1\31"+
    "\3\30\1\32\1\30\1\33\2\30\15\31\1\30\2\31"+
    "\2\30\1\31\1\30\1\34\40\0\2\7\7\0\15\7"+
    "\1\0\2\7\2\0\1\7\3\0\2\7\7\0\14\7"+
    "\1\35\1\0\2\7\2\0\1\7\2\0\32\36\1\12"+
    "\5\36\2\13\7\36\15\13\1\36\2\13\1\12\1\36"+
    "\1\13\5\36\1\37\1\15\25\36\1\12\7\36\1\15"+
    "\26\36\1\12\5\36\2\13\7\36\1\13\1\40\1\13"+
    "\1\41\11\13\1\36\2\13\1\12\1\36\1\13\2\36"+
    "\1\0\2\20\7\0\15\20\1\0\2\20\2\0\1\20"+
    "\5\0\1\42\1\22\35\0\1\22\33\0\5\25\1\0"+
    "\31\25\3\0\1\43\2\0\1\44\30\0\5\25\1\45"+
    "\31\25\5\46\1\6\32\46\2\31\2\46\1\6\4\46"+
    "\15\31\1\46\2\31\2\46\1\31\2\46\5\30\1\6"+
    "\2\30\2\46\25\30\5\46\1\6\27\46\1\47\1\46"+
    "\1\0\2\7\7\0\15\7\1\0\1\7\1\50\2\0"+
    "\1\7\2\0\1\36\2\13\7\36\2\13\1\51\12\13"+
    "\1\36\2\13\1\12\1\36\1\13\3\36\2\13\7\36"+
    "\11\13\1\52\3\13\1\36\2\13\1\12\1\36\1\13"+
    "\2\36\3\0\1\44\1\0\1\53\32\0\2\7\7\0"+
    "\2\7\1\54\12\7\1\0\2\7\2\0\1\7\2\0"+
    "\1\36\2\13\7\36\3\13\1\55\11\13\1\36\2\13"+
    "\1\12\1\36\1\13\3\36\2\13\7\36\12\13\1\56"+
    "\2\13\1\36\2\13\1\12\1\36\1\13\2\36\1\0"+
    "\2\7\7\0\2\7\1\57\12\7\1\0\2\7\2\0"+
    "\1\7\2\0\1\36\2\13\7\36\4\13\1\60\10\13"+
    "\1\36\2\13\1\12\1\36\1\13\3\36\2\13\7\36"+
    "\13\13\1\61\1\13\1\36\2\13\1\12\1\36\1\13"+
    "\3\36\2\13\7\36\5\13\1\62\7\13\1\36\2\13"+
    "\1\12\1\36\1\13\3\36\2\13\7\36\15\13\1\36"+
    "\2\13\1\12\1\36\1\63\2\36\1\64\2\65\5\64"+
    "\2\36\15\65\1\64\2\65\1\66\1\64\1\65\2\64"+
    "\1\36\2\13\1\67\6\36\15\13\1\36\2\13\1\12"+
    "\1\36\1\13\22\36\1\70\11\36\1\12\5\36\2\13"+
    "\7\36\6\13\1\71\6\13\1\36\2\13\1\12\1\36"+
    "\1\13\5\36\1\67\26\36\1\12\25\36\1\72\10\36"+
    "\1\12\5\36\2\13\7\36\7\13\1\73\5\13\1\36"+
    "\2\13\1\12\1\36\1\13\17\36\1\74\14\36\1\12"+
    "\5\36\2\13\7\36\3\13\1\75\11\13\1\36\2\13"+
    "\1\12\1\36\1\13\2\36\10\76\2\36\20\76\1\77"+
    "\5\76\2\100\5\76\2\36\15\100\1\76\2\100\1\77"+
    "\1\76\1\100\2\76\22\36\1\101\7\36\1\12\5\36"+
    "\2\13\7\36\10\13\1\102\4\13\1\36\2\13\1\12"+
    "\1\36\1\13\25\36\1\103\6\36\1\12\5\36\2\13"+
    "\7\36\11\13\1\104\3\13\1\36\2\13\1\12\1\36"+
    "\1\13\26\36\1\105\5\36\1\12\5\36\2\13\7\36"+
    "\12\13\1\106\2\13\1\36\2\13\1\12\1\36\1\13"+
    "\27\36\1\107\4\36\1\12\5\36\2\13\7\36\13\13"+
    "\1\110\1\13\1\36\2\13\1\12\1\36\1\13\17\36"+
    "\1\111\14\36\1\12\5\36\2\13\7\36\3\13\1\112"+
    "\11\13\1\36\2\13\1\12\1\36\1\13\30\36\1\113"+
    "\3\36\1\12\5\36\2\13\7\36\14\13\1\114\1\36"+
    "\2\13\1\12\1\36\1\13\27\36\1\115\4\36\1\12"+
    "\5\36\2\13\7\36\13\13\1\116\1\13\1\36\2\13"+
    "\1\12\1\36\1\13\31\36\1\117\2\36\1\12\5\36"+
    "\2\13\7\36\15\13\1\117\2\13\1\12\1\36\1\13"+
    "\2\36";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1922];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\1\1\0\1\11\2\1\1\11\11\1\2\11"+
    "\11\1\2\0\2\1\3\0\1\11\1\0\4\1\1\11"+
    "\10\1\1\0\3\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\2\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[79];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	String variable = "", valor = "";


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 154) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { valor += yytext();
            } 
            // fall through
          case 15: break;
          case 2: 
            { System.out.print(yytext());
            } 
            // fall through
          case 16: break;
          case 3: 
            { System.out.print(yytext() + "_rmj");
            } 
            // fall through
          case 17: break;
          case 4: 
            { System.out.print(yytext());
					 yybegin(METODO);
            } 
            // fall through
          case 18: break;
          case 5: 
            { yybegin(DECLARACION);
            } 
            // fall through
          case 19: break;
          case 6: 
            { 
            } 
            // fall through
          case 20: break;
          case 7: 
            { System.out.print(yytext());
					 yybegin(YYINITIAL);
            } 
            // fall through
          case 21: break;
          case 8: 
            { variable = yytext();
            } 
            // fall through
          case 22: break;
          case 9: 
            { yybegin(TEXTO);
            } 
            // fall through
          case 23: break;
          case 10: 
            { TablaSimbolos.put(variable, valor);
			 			 yybegin(METODO);
            } 
            // fall through
          case 24: break;
          case 11: 
            { TablaSimbolos.put(variable, valor);
							 yybegin(DECLARACION);
            } 
            // fall through
          case 25: break;
          case 12: 
            { System.out.print(TablaSimbolos.get(yytext()));
            } 
            // fall through
          case 26: break;
          case 13: 
            { System.out.print(yytext());
						 yybegin(METODO);
            } 
            // fall through
          case 27: break;
          case 14: 
            { System.out.print(yytext());
					 yybegin(SALIDA);
            } 
            // fall through
          case 28: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
