/* The following code was generated by JFlex 1.7.0 */


/* Vacío */


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>rmj.lex</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int METODO = 2;
  public static final int DECLARACION = 4;
  public static final int TEXTO = 6;
  public static final int SALIDA = 8;
  public static final int SUSTITUCION = 10;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5, 5
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\12\0\1\7\1\10\1\10\1\10\22\0\1\3\1\0\1\34\5\0"+
    "\1\26\1\36\1\0\1\5\1\35\3\0\12\2\1\0\1\37\1\0"+
    "\1\4\3\0\22\1\1\11\7\1\1\0\1\6\2\0\1\1\1\0"+
    "\1\30\1\1\1\27\1\1\1\15\1\1\1\33\1\1\1\23\2\1"+
    "\1\25\1\16\1\24\1\17\1\21\1\1\1\22\1\13\1\14\1\20"+
    "\3\1\1\12\1\1\1\31\1\0\1\32\7\0\1\10\u1fa2\0\1\10"+
    "\1\10\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\3\2\2\3\1\4\1\2\1\5\1\2"+
    "\1\6\1\5\1\7\1\10\1\2\1\6\1\11\1\12"+
    "\2\1\1\5\1\2\1\13\2\2\1\14\3\2\1\15"+
    "\1\3\2\0\2\5\1\0\1\1\1\16\1\17\1\3"+
    "\2\5\1\3\2\5\1\2\4\5\1\0\1\5\1\2"+
    "\1\5\1\0\1\5\1\0\1\5\1\0\1\5\1\0"+
    "\1\2\1\5\1\0\1\5\1\0\1\5\1\0\1\5"+
    "\1\0\1\5\1\0\1\5\1\0\1\20\1\5\1\0"+
    "\1\5";

  private static int [] zzUnpackAction() {
    int [] result = new int[81];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\40\0\100\0\140\0\200\0\240\0\300\0\340"+
    "\0\u0100\0\300\0\u0120\0\u0140\0\u0160\0\u0180\0\u01a0\0\u0120"+
    "\0\u01c0\0\u01e0\0\u0200\0\300\0\300\0\u0220\0\u0240\0\300"+
    "\0\u0260\0\u0280\0\u02a0\0\u02c0\0\300\0\u02e0\0\u0300\0\u0320"+
    "\0\300\0\u0340\0\u0120\0\u0160\0\u0360\0\u0380\0\u01e0\0\300"+
    "\0\300\0\300\0\u03a0\0\u03c0\0\u03e0\0\u0400\0\u0420\0\u0440"+
    "\0\340\0\u0460\0\u0480\0\u04a0\0\u04c0\0\u04e0\0\u0500\0\u04e0"+
    "\0\u0520\0\u0540\0\u0560\0\u0580\0\u05a0\0\u05c0\0\u05e0\0\u0600"+
    "\0\u0600\0\u0620\0\u0640\0\u0660\0\u0680\0\u06a0\0\u06c0\0\u06e0"+
    "\0\u0700\0\u0720\0\u0740\0\u0760\0\u0780\0\u0120\0\u07a0\0\u07c0"+
    "\0\u07e0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[81];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\7\1\10\7\7\15\10\1\7\1\11\1\10\1\12"+
    "\1\7\1\10\4\7\1\13\1\14\1\13\1\15\1\16"+
    "\4\13\1\17\14\14\1\13\2\14\1\13\1\20\1\14"+
    "\4\13\1\7\1\21\1\7\1\22\1\23\2\7\1\24"+
    "\1\7\15\21\1\7\2\21\2\7\1\21\1\25\1\24"+
    "\1\7\1\24\6\26\1\27\25\26\1\30\3\26\1\31"+
    "\1\32\1\31\1\33\1\31\1\23\1\34\2\31\15\32"+
    "\1\31\2\32\2\31\1\32\1\35\1\31\1\36\1\7"+
    "\6\37\1\40\25\37\1\41\3\37\41\0\2\10\6\0"+
    "\15\10\1\0\2\10\2\0\1\10\5\0\2\10\6\0"+
    "\14\10\1\42\1\0\2\10\2\0\1\10\4\0\31\43"+
    "\1\13\7\43\2\14\6\43\15\14\1\43\2\14\1\13"+
    "\1\43\1\14\7\43\1\44\1\16\24\43\1\13\11\43"+
    "\1\16\25\43\1\13\7\43\2\14\6\43\1\14\1\45"+
    "\1\14\1\46\11\14\1\43\2\14\1\13\1\43\1\14"+
    "\4\43\1\0\2\21\6\0\15\21\1\0\2\21\2\0"+
    "\1\21\7\0\1\47\1\23\36\0\1\23\34\0\34\26"+
    "\1\0\37\26\1\50\3\26\5\31\1\0\26\31\1\0"+
    "\1\31\2\0\1\31\2\32\2\31\1\0\3\31\15\32"+
    "\1\31\2\32\2\31\1\32\1\0\1\31\2\0\3\31"+
    "\1\33\1\31\1\23\26\31\1\0\1\31\2\0\5\31"+
    "\1\7\26\31\1\51\1\31\2\7\37\0\1\52\34\37"+
    "\1\0\37\37\1\7\3\37\1\0\2\10\6\0\15\10"+
    "\1\0\1\10\1\53\2\0\1\10\4\0\1\43\2\14"+
    "\6\43\2\14\1\54\12\14\1\43\2\14\1\13\1\43"+
    "\1\14\5\43\2\14\6\43\11\14\1\55\3\14\1\43"+
    "\2\14\1\13\1\43\1\14\4\43\1\0\2\10\6\0"+
    "\2\10\1\56\12\10\1\0\2\10\2\0\1\10\4\0"+
    "\1\43\2\14\6\43\3\14\1\57\11\14\1\43\2\14"+
    "\1\13\1\43\1\14\5\43\2\14\6\43\12\14\1\60"+
    "\2\14\1\43\2\14\1\13\1\43\1\14\4\43\1\0"+
    "\2\10\6\0\2\10\1\61\12\10\1\0\2\10\2\0"+
    "\1\10\4\0\1\43\2\14\6\43\4\14\1\62\10\14"+
    "\1\43\2\14\1\13\1\43\1\14\5\43\2\14\6\43"+
    "\13\14\1\63\1\14\1\43\2\14\1\13\1\43\1\14"+
    "\5\43\2\14\6\43\5\14\1\64\7\14\1\43\2\14"+
    "\1\13\1\43\1\14\5\43\2\14\6\43\15\14\1\43"+
    "\2\14\1\13\1\43\1\65\4\43\1\66\2\67\4\66"+
    "\2\43\15\67\1\66\2\67\1\70\1\66\1\67\4\66"+
    "\1\43\2\14\1\71\5\43\15\14\1\43\2\14\1\13"+
    "\1\43\1\14\23\43\1\72\11\43\1\13\7\43\2\14"+
    "\6\43\6\14\1\73\6\14\1\43\2\14\1\13\1\43"+
    "\1\14\7\43\1\71\25\43\1\13\26\43\1\74\10\43"+
    "\1\13\7\43\2\14\6\43\7\14\1\75\5\14\1\43"+
    "\2\14\1\13\1\43\1\14\20\43\1\76\14\43\1\13"+
    "\7\43\2\14\6\43\3\14\1\77\11\14\1\43\2\14"+
    "\1\13\1\43\1\14\4\43\7\100\2\43\20\100\1\101"+
    "\7\100\2\102\4\100\2\43\15\102\1\100\2\102\1\101"+
    "\1\100\1\102\4\100\21\43\1\103\7\43\1\13\7\43"+
    "\2\14\6\43\10\14\1\104\4\14\1\43\2\14\1\13"+
    "\1\43\1\14\26\43\1\105\6\43\1\13\7\43\2\14"+
    "\6\43\11\14\1\106\3\14\1\43\2\14\1\13\1\43"+
    "\1\14\27\43\1\107\5\43\1\13\7\43\2\14\6\43"+
    "\12\14\1\110\2\14\1\43\2\14\1\13\1\43\1\14"+
    "\30\43\1\111\4\43\1\13\7\43\2\14\6\43\13\14"+
    "\1\112\1\14\1\43\2\14\1\13\1\43\1\14\20\43"+
    "\1\113\14\43\1\13\7\43\2\14\6\43\3\14\1\114"+
    "\11\14\1\43\2\14\1\13\1\43\1\14\31\43\1\115"+
    "\1\116\2\43\1\13\7\43\2\14\6\43\14\14\1\117"+
    "\1\116\2\14\1\13\1\43\1\14\30\43\1\120\4\43"+
    "\1\13\7\43\2\14\6\43\13\14\1\121\1\14\1\43"+
    "\2\14\1\13\1\43\1\14\32\43\1\116\2\43\1\13"+
    "\7\43\2\14\6\43\15\14\1\116\2\14\1\13\1\43"+
    "\1\14\4\43";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2048];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\3\1\1\11\2\1\1\11\11\1\2\11\2\1"+
    "\1\11\4\1\1\11\3\1\1\11\1\1\2\0\2\1"+
    "\1\0\3\11\13\1\1\0\3\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\2\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\2\1\1\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[81];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	String variable = "", valor = "";


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 156) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { valor += yytext();
            } 
            // fall through
          case 17: break;
          case 2: 
            { System.out.print(yytext());
            } 
            // fall through
          case 18: break;
          case 3: 
            { System.out.print(yytext() + "_rmj");
            } 
            // fall through
          case 19: break;
          case 4: 
            { System.out.print(yytext());
					 yybegin(METODO);
            } 
            // fall through
          case 20: break;
          case 5: 
            { yybegin(DECLARACION);
            } 
            // fall through
          case 21: break;
          case 6: 
            { 
            } 
            // fall through
          case 22: break;
          case 7: 
            { System.out.print(yytext());
					 yybegin(YYINITIAL);
            } 
            // fall through
          case 23: break;
          case 8: 
            { variable = yytext();
            } 
            // fall through
          case 24: break;
          case 9: 
            { TablaSimbolos.put(variable, valor);
			 		 yybegin(METODO);
            } 
            // fall through
          case 25: break;
          case 10: 
            { yybegin(TEXTO);
            } 
            // fall through
          case 26: break;
          case 11: 
            { System.out.print(TablaSimbolos.get(yytext()));
            } 
            // fall through
          case 27: break;
          case 12: 
            { yybegin(SUSTITUCION);
            } 
            // fall through
          case 28: break;
          case 13: 
            { yybegin(SALIDA);
            } 
            // fall through
          case 29: break;
          case 14: 
            { System.out.print(yytext()); yybegin(SUSTITUCION);
            } 
            // fall through
          case 30: break;
          case 15: 
            { System.out.print("\"" + yytext());
							 yybegin(METODO);
            } 
            // fall through
          case 31: break;
          case 16: 
            { System.out.print(yytext() + "\"");
					 yybegin(SALIDA);
            } 
            // fall through
          case 32: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
